# Generated by Django 4.0.6 on 2022-08-06 15:51

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_footer', models.CharField(max_length=200)),
                ('selecionado', core.fields.UniqueBooleanField()),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('servicio_1', models.CharField(max_length=50)),
                ('servicio_2', models.CharField(max_length=50)),
                ('servicio_3', models.CharField(max_length=50)),
                ('servicio_4', models.CharField(max_length=50)),
                ('link_1_nombre', models.CharField(max_length=50)),
                ('link_2_nombre', models.CharField(max_length=50)),
                ('link_3_nombre', models.CharField(max_length=50)),
                ('link_4_nombre', models.CharField(max_length=50)),
                ('link_1_url', models.URLField()),
                ('link_2_url', models.URLField()),
                ('link_3_url', models.URLField()),
                ('link_4_url', models.URLField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=200)),
                ('selecionado', core.fields.UniqueBooleanField()),
                ('mostrar_dolar', models.BooleanField(default=True)),
                ('titulo_principal', models.CharField(max_length=200)),
                ('imagen_1', models.ImageField(upload_to='images-home')),
                ('imagen_2', models.ImageField(upload_to='images-home')),
                ('imagen_Servicios', models.ImageField(upload_to='images-home')),
                ('titulo1', models.CharField(max_length=200)),
                ('texto1', models.TextField()),
                ('titulo2', models.CharField(max_length=200)),
                ('texto2', models.TextField()),
                ('servicio_1', models.CharField(max_length=50)),
                ('servicio_2', models.CharField(max_length=50)),
                ('servicio_3', models.CharField(max_length=50)),
                ('servicio_4', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tema Home',
                'verbose_name_plural': 'Temas Home',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='images-services')),
                ('caption', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
