# Generated by Django 4.0.6 on 2022-09-23 00:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_home_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='articulo_servicios',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
