# Generated by Django 4.0.6 on 2022-09-24 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_home_articulo_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='articulo_sobre_mi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
