# Generated by Django 4.0.6 on 2022-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_footer_facebook_footer_github_footer_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='mi_nombre',
            field=models.CharField(default='MACARENA FUCILIERI', max_length=200),
            preserve_default=False,
        ),
    ]
