# Generated by Django 4.0.6 on 2022-12-23 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 13, 0, 44, 892642)),
        ),
    ]
