# Generated by Django 4.0.6 on 2022-12-23 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contacto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.TimeField(default=datetime.datetime(2022, 12, 23, 13, 30, 33, 814802), editable=False),
        ),
    ]
