# Generated by Django 4.0.6 on 2022-12-23 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contacto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 13, 31, 45, 826754), editable=False),
        ),
    ]
